## Importing NumPy

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [26]:
b = np.array([[10,20,30],[40,50,60],[70,80,90],['a','b','c']])
print(b)

[['10' '20' '30']
 ['40' '50' '60']
 ['70' '80' '90']
 ['a' 'b' 'c']]


### Get dimension of the array

In [38]:
print(a.ndim)
print(b.ndim)

1
2


### Get shape (rows, columns)

In [39]:
print(a.shape)
print(b.shape)

(4,)
(4, 3)


In [31]:
lst1 = ['a','b','c','t']
lst2 = ['d','e','f','y']
lst3 = ['g','h','i','u']

arr = np.array([lst1,lst2,lst3])
print(arr)
print(arr.ndim)
print(arr.shape)

[['a' 'b' 'c' 't']
 ['d' 'e' 'f' 'y']
 ['g' 'h' 'i' 'u']]
2
(3, 4)


### Reshaping

In [7]:
# when reshaping the total should be same [ 3*4=12  2*6=12  2*2*3=12 ] ------> like so

a = np.array([['a','b','c','t'],['d','e','f','y'],['g','h','i','u']])

print(a)
print(a.shape,'\n')

print(a.reshape(2,6))         # 2 rows 6 columns          
print(a.reshape(2,6).shape,'\n')

print(a.reshape(2,2,3))
print(a.reshape(2,2,3).shape)

[['a' 'b' 'c' 't']
 ['d' 'e' 'f' 'y']
 ['g' 'h' 'i' 'u']]
(3, 4) 

[['a' 'b' 'c' 't' 'd' 'e']
 ['f' 'y' 'g' 'h' 'i' 'u']]
(2, 6) 

[[['a' 'b' 'c']
  ['t' 'd' 'e']]

 [['f' 'y' 'g']
  ['h' 'i' 'u']]]
(2, 2, 3)


### Getting specific elements aka Indexing

In [8]:
ab = np.array([['a','b','c','t'],['d','e','f','y'],['g','h','i','u']])
cd = np.array([85,41,63,52,10])

print(ab,'\n')
print(cd)

[['a' 'b' 'c' 't']
 ['d' 'e' 'f' 'y']
 ['g' 'h' 'i' 'u']] 

[85 41 63 52 10]


In [5]:
print(cd[2],'\n')
print(ab[2,3],'\n')            # [rows, columns]
print(ab[:2,:2],'\n')
print(ab[1:2,1:3])

63 

u 

[['a' 'b']
 ['d' 'e']] 

[['e' 'f']]


### Change an element

In [161]:
ab = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(ab)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [162]:
ab[0,2] = 66                     # replace specific value
print(ab,'\n')

ab[:,1] = 80                     # replace all values
print(ab,'\n')

ab[2,:] = 100,200,300,400        # replace multiple values
print(ab)

[[ 1  2 66  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1 80 66  4]
 [ 5 80  7  8]
 [ 9 80 11 12]] 

[[  1  80  66   4]
 [  5  80   7   8]
 [100 200 300 400]]


### Creating arrays

In [178]:
a = np.zeros((4))     # creates an array of 0s
print(a)

[0. 0. 0. 0.]


In [9]:
x = np.ones((3,2))                     # creates an array of 1s
print(x,'\n')                               # default value is set to float

y = np.ones((3,2), dtype=int)          # changing to int
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[1 1]
 [1 1]
 [1 1]]


In [80]:
# create an array of specific number. syntax --> (rows,columns)number

np.full((2,3),83)

array([[83, 83, 83],
       [83, 83, 83]])

In [12]:
# create random array of decimals

np.random.rand(2,2)

array([[0.878182  , 0.14637109],
       [0.6033309 , 0.34653892]])

In [186]:
# Create an array of int. 1st parametr is the lowest value and 2nd parametr is the highest value.
# size is rows and colmns

np.random.randint(2,5, size=(3,2))

array([[2, 4],
       [2, 2],
       [2, 3]])

In [18]:
a = np.random.randint(10,30,6)                      # creates 1d array with random 6 elements from 10 to 30
b = np.random.randint(10,30,6).reshape(2,3)         # Reshape the array (rows, columns)

print(a,'\n',b)

[22 28 14 26 23 23] 
 [[13 29 14]
 [24 11 15]]


In [19]:
ab = np.arange(0,9)                            # creates an array from 0 to 9.
cd = np.arange(1,21, step=2).reshape(5,2)      # step skips an element of given number

print(ab)
print(cd)

[0 1 2 3 4 5 6 7 8]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


### Copying arrays

In [14]:
a = np.array([1,2,3,4,])
print(a)

b = a.copy()
print(b,'\n')

b[1] = 100

print(b)       
print(a)

[1 2 3 4]
[1 2 3 4] 

[  1 100   3   4]
[1 2 3 4]


### Maths

In [20]:
a = np.array([20,34,45,93])

print(a)
print(a + 2)                   # Add
print(a - 2)                   # Subtract
print(a * 2)                   # Multiply
print(a / 2)                   # Divide
print(a > 30)                  # Return boolean value
print(a[a > 30])               # Returns value

[20 34 45 93]
[22 36 47 95]
[18 32 43 91]
[ 40  68  90 186]
[10.  17.  22.5 46.5]
[False  True  True  True]
[34 45 93]


In [46]:
a1 = np.full((2,3),4)
b1 = np.full((3,2),3)

print(a1,'\n')
print(b1,'\n')
print(np.matmul(a1,b1))   # Matrix Multiplication

[[4 4 4]
 [4 4 4]] 

[[3 3]
 [3 3]
 [3 3]] 

[[36 36]
 [36 36]]


In [63]:
ab = np.array([[2,3,8,5],[7,11,3,6]])

print(ab)
print(np.min(ab))     # minimum value
print(np.max(ab))     # maximum value
print(np.sum(ab))     # adds all the elements

[[ 2  3  8  5]
 [ 7 11  3  6]]
2
11
45


### Retrieve elements using loop

In [85]:
ar = np.full((2,3),4)

print(ar,'\n')

for x in ar.flat:                        # returns in list
    print(x)

[[4 4 4]
 [4 4 4]] 

4
4
4
4
4
4


### Vertical and Horizontal Stacking

In [86]:
ar1 = ([1,2,3,4])
ar2 = ([5,6,7,8])

print(np.vstack((ar1,ar2,ar1,ar2)),'\n')        # vertical stacking
print(np.hstack((ar1,ar2)))                     # horizontal stacking

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]] 

[1 2 3 4 5 6 7 8]


### Loading data from file

In [94]:
x = np.genfromtxt('data.txt', delimiter=',', dtype=int)   # delimiter is what separetes the data in the file
print(x)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
